---
name: Telegraf2Hassio
version: 0.1.0
slug: telegraf2hassio
description: Turn telegraf metrics into hassio self-discovered sensors
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
url: https://github.com/joaofl/hassio-addons/tree/master/telegraf2hassio
startup: application
services:
- mqtt:need
boot: auto
host_network: true
devices:
- "/dev/mem"
map:
- config:rw
- share:rw
options:
  mqtt_broker: localhost
  mqtt_port: 1883
  mqtt_user:
  mqtt_pass:
  telegraf_topic: telegraf/#
schema:
  mqtt_broker: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: str
  telegraf_topic: str
